version: '3.8'
services:
  
  database:
    image: postgres
    container_name: tailor_db
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  redis:
    image: redis:7-alpine

  celery_worker:
    build:
      context: .
    command: celery -A main worker -l INFO
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/app
    depends_on:
      - redis
      - database

  flower:
    build: 
      context: .
    command: celery flower -l INFO
    env_file:
      - .env
    ports:
      - '5557:5555'
    depends_on:
      - redis
      - database


  tailor:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    image: tailor:tailor_app
    container_name: tailor_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - database
      - pgadmin
      - redis
