# Generated by Django 4.0.6 on 2022-08-28 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import store_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "branch_name",
                    models.CharField(max_length=200, verbose_name="branch name"),
                ),
                ("location", models.TextField()),
                (
                    "street_name",
                    models.CharField(max_length=150, verbose_name="branch street name"),
                ),
                (
                    "digital_address",
                    models.CharField(
                        max_length=15, verbose_name="branch digital address"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Design",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="design style"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="style description"
                    ),
                ),
                ("fabric_available", models.BooleanField(default=False)),
                (
                    "price_with_store_fabric",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "price_without_store_fabric",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "store_branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branch_designs",
                        to="store_api.branch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("about", models.TextField(blank=True, null=True)),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("FPBP", "full_payment_before_processing"),
                            ("PPBP", "part_payment_before_processing"),
                        ],
                        default="FPBP",
                        max_length=50,
                    ),
                ),
                (
                    "part_payment_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "Pending"), ("A", "Accepted")],
                        default="P",
                        max_length=15,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="store creation date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="store last updated"
                    ),
                ),
                (
                    "store_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=store_api.models.media_uploads,
                        verbose_name="design image",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(max_length=255, verbose_name="alternative text"),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="default design image"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="upload date"),
                ),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_images",
                        to="store_api.design",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="branch",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="store_branch",
                to="store_api.store",
            ),
        ),
        migrations.AddConstraint(
            model_name="store",
            constraint=models.CheckConstraint(
                check=models.Q(("part_payment_percentage__lte", 0.8)),
                name="Part payment percentage should be less than or equal 0.8",
            ),
        ),
    ]
