# Generated by Django 4.0.6 on 2022-08-05 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='design style')),
                ('description', models.TextField(blank=True, null=True, verbose_name='style description')),
            ],
        ),
        migrations.CreateModel(
            name='DesignDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=299.99, max_digits=10)),
                ('design', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_details', to='store_api.design')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('about', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'P'), ('accepted', 'A')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='store creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='store last updated')),
                ('design', models.ManyToManyField(blank=True, through='store_api.DesignDetail', to='store_api.design')),
                ('store_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images/', verbose_name='design image')),
                ('alt_text', models.CharField(max_length=255, verbose_name='alternative text')),
                ('is_feature', models.BooleanField(default=False, verbose_name='default design image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='upload date')),
                ('design_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_images', to='store_api.designdetail')),
            ],
        ),
        migrations.AddField(
            model_name='designdetail',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_design_details', to='store_api.store'),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=200, verbose_name='branch name')),
                ('location', models.TextField()),
                ('street_name', models.CharField(max_length=150, verbose_name='branch street name')),
                ('digital_address', models.CharField(max_length=15, verbose_name='branch digital address')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_branch', to='store_api.store')),
            ],
        ),
    ]
