# Generated by Django 4.0.6 on 2022-07-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='design',
            field=models.ManyToManyField(null=True, related_name='store_designs', through='store_api.DesignDetail', to='store_api.design'),
        ),
    ]
