# Generated by Django 4.0.6 on 2022-07-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0002_alter_store_design'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='design',
            field=models.ManyToManyField(null=True, through='store_api.DesignDetail', to='store_api.design'),
        ),
    ]
