# Generated by Django 4.0.6 on 2022-08-23 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantity', models.DecimalField(decimal_places=0, default=1, max_digits=6)),
                ('fabric_source', models.CharField(choices=[('from_store', 'Store'), ('from_me', 'Personal')], default='from_me', max_length=10)),
                ('order_status', models.CharField(choices=[('Received', 'Order Received'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Received', max_length=50)),
                ('payment_status', models.CharField(choices=[('Not Paid', 'Unpaid'), ('Part Payment', 'Part'), ('Full Payment', 'Processing')], default='Not Paid', max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('design', models.ManyToManyField(related_name='order_designs', to='store_api.design')),
                ('store_branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store_api.branch')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('paid_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
