# Generated by Django 4.0.6 on 2022-08-29 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('NP', 'Unpaid'), ('PP', 'Part'), ('FP', 'Processing')], default='NP', max_length=100)),
                ('order_status', models.CharField(choices=[('R', 'Order Received'), ('P', 'Processing'), ('C', 'Completed'), ('D', 'Delivered'), ('Cancelled', 'Cancelled')], default='R', max_length=50)),
                ('ordered_on', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('store_branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store_api.branch')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('paid_on', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_source', models.CharField(choices=[('FS', 'Store'), ('FM', 'Personal')], default='FM', max_length=10)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_item_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('designs', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store_api.design')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='orders.order')),
            ],
        ),
    ]
