# Generated by Django 4.0.6 on 2022-08-29 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='designs',
            new_name='design',
        ),
    ]
