# Generated by Django 4.0.6 on 2022-08-03 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(default='+233......', max_length=30, verbose_name='Phone Number')),
                ('about_me', models.TextField(default='say something about yourself', verbose_name='About me')),
                ('profile_photo', models.ImageField(default='/profile_default.png', upload_to='', verbose_name='Profile Photo')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, verbose_name='Gender')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neck', models.IntegerField(verbose_name='Around neck')),
                ('bust', models.IntegerField(verbose_name='Bust area')),
                ('arm_length', models.IntegerField(verbose_name='Arm length short')),
                ('long_sleeve', models.IntegerField(verbose_name='Arm length long')),
                ('bicep', models.IntegerField(verbose_name='Bicep')),
                ('wrist', models.IntegerField(verbose_name='Wrist')),
                ('torso', models.IntegerField(verbose_name='Torso length')),
                ('waist', models.IntegerField(verbose_name='Waist')),
                ('hips', models.IntegerField(verbose_name='hips')),
                ('waist_to_above_knee', models.IntegerField(verbose_name='Skirt/ Shorts length')),
                ('waist_to_below_knee', models.IntegerField(verbose_name='Trouser length')),
                ('calf', models.IntegerField(verbose_name='Calf')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(default='GH', max_length=2, verbose_name='Country')),
                ('street', models.CharField(blank=True, max_length=200, null=True)),
                ('house_number', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(max_length=50)),
                ('city', models.CharField(default='Accra', max_length=180, verbose_name='City')),
                ('digital_address', models.CharField(max_length=15)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
