# Generated by Django 4.0.6 on 2022-08-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='store_owner',
            field=models.BooleanField(default=False, help_text='Are you a Store Owner?', verbose_name='Store Owner'),
        ),
    ]
